services:
  postgres:
    image: postgres:16-alpine
    container_name: svu_food_delivery_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: food_delivery
    ports:
      - "5432:5432"
    volumes:
      - svu_food_delivery_pgdata:/var/lib/postgresql/data

volumes:
  svu_food_delivery_pgdata:
